### ISSUE TITLE
sop/asn1 update needed

### ISSUE THREAD

**Issue by aliqasemzadeh** [Fenguoz/bsc-php#1]
Hi
When I want to install it I get this error.
Please update sop/asn1.

 Problem 1
    - Root composer.json requires fenguoz/bsc-php ^0.1.0 -> satisfiable by fenguoz/bsc-php[0.1.0].
    - fenguoz/bsc-php 0.1.0 requires sop/asn1 ^3.3 -> found sop/asn1[3.3.0, ..., 3.4.3] but it conflicts with your root composer.json require (^4.1).

**Comment by Fenguoz** [comment]
PHP version？

**Comment by aliqasemzadeh** [comment]
8.2

**Comment by Fenguoz** [comment]
composer require fenguoz/bsc-php ~2.0

**Comment by aliqasemzadeh** [comment]
@Fenguoz 
````
 Problem 1
    - Root composer.json requires fenguoz/bsc-php ~2.0 -> satisfiable by fenguoz/bsc-php[2.0.0].
    - fenguoz/bsc-php 2.0.0 requires sop/asn1 ^3.3 -> found sop/asn1[3.3.0, ..., 3.4.3] but it conflicts with your root composer.json require (^4.1).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific version
````

Yet I get this errror.

**Comment by Fenguoz** [comment]
[tag2.1.0](https://github.com/Fenguoz/bsc-php/releases/tag/2.1.0) :Optimize the low version of guzzle.

**Comment by aliqasemzadeh** [comment]
@Fenguoz 
Then we need to 
`composer require fenguoz/bsc-php ~2.1`

**Comment by aliqasemzadeh** [comment]
Also I did : https://github.com/aliqasemzadeh/bsc-php to get work in php 8.2 and laravel 9.
