### ISSUE TITLE
the same private key is always displayed

### ISSUE THREAD

**Issue by kendol07** [Fenguoz/bsc-php#3]
the functions function revertAccountByMnemonic() and function revertAccountByMnemonic() always return the same private key and address

**Comment by Fenguoz** [comment]
revertAccountByPrivateKey and revertAccountByMnemonic?

**Comment by kendol07** [comment]
if I revert an account by Mnemonic or if I generate a new Mnemonic it also always shows the same private key and address. Apparently there is a mnemonic phrase that is by default in everything and is not being changed.

**Comment by Fenguoz** [comment]
The issue has been resolved. [Solve BIP44 parameter passing format error](https://github.com/Fenguoz/bsc-php/commit/f4f46f56a323d2b6ea42619bb61cd8bc5324e8ce)

**Comment by kendol07** [comment]
Thank you, I confirm that it is solved
